# Generated by Django 3.2.12 on 2023-05-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('SU1', 'Поддержка (1 линия)'), ('SU2', 'Поддержка (2 линия)'), ('SAL', 'Менеджер по продажам'), ('CTO', 'Технический директор')], default=None, max_length=3)),
                ('age', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=128)),
                ('job_start', models.DateField()),
                ('job_format', models.CharField(choices=[('DST', 'Удаленно'), ('OFC', 'Офис'), ('HYB', 'Гибридный')], default='OFC', max_length=3)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.employee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('CALL', 'Звонки'), ('IUPD', 'Актуализированые контактные данные'), ('PROM', 'Обещания клиентов'), ('REQU', 'Заявки клиентов'), ('MEET', 'Встречи'), ('PILO', 'Запущенные пилоты'), ('RVIE', 'Глобальные ревью'), ('AGRV', 'Валидации договоров'), ('MKRP', 'Формирование внутреннего отчёта'), ('CSTL', 'Письма заказчикам'), ('RSKR', 'Отчет по оценке рисков'), ('TCHT', 'Подготовка ТЗ'), ('AUDT', 'Аудит технологических активов'), ('SPRP', 'Планирование спринта')], default=None, max_length=4)),
                ('goal', models.IntegerField()),
                ('result', models.IntegerField()),
                ('monthPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='stats.monthplan')),
            ],
            options={
                'ordering': ['task'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='messengers',
            field=models.ManyToManyField(to='stats.Messenger'),
        ),
    ]
