# Generated by Django 3.2.12 on 2023-05-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='monthPlan',
            new_name='month_plan',
        ),
    ]
