# Generated by Django 3.2.12 on 2023-05-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_monthplan_plan_month_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_plans', to='stats.employee'),
        ),
    ]
